package main

import (
	"context"
	"log/slog"
)

type russianLogHandler struct {
	slog.Handler
}

func (h russianLogHandler) Handle(ctx context.Context, record slog.Record) error {
	if message, ok := russianLogMessages[record.Message]; ok {
		record.Message = message
	}
	return h.Handler.Handle(ctx, record)
}

var russianLogMessages = map[string]string{
	"archive course failed":                        "архивация курса не выполнена",
	"archive quiz failed":                          "архивация теста не выполнена",
	"attempt certificate auto issue failed":        "автовыдача сертификата после попытки не выполнена",
	"attempt certificate auto issued":              "сертификат автоматически выдан после попытки",
	"attempt certificate enrollment lookup failed": "enrollment для автовыдачи сертификата не найден",
	"audit log marshal payload failed":             "payload audit log не сериализован",
	"audit log write failed":                       "audit log не записан",
	"audit webhook outbox claim failed":            "webhook outbox audit log не взят в обработку",
	"audit webhook outbox dispatch failed":         "webhook outbox audit log не отправлен",
	"audit webhook outbox dispatched":              "webhook outbox audit log отправлен",
	"audit webhook outbox mark failure failed":     "ошибка webhook outbox audit log не сохранена",
	"audit webhook outbox mark success failed":     "успешная отправка webhook outbox audit log не сохранена",
	"auth middleware rejected request":             "запрос отклонён middleware авторизации",
	"auto certificate issuance failed":             "автовыдача сертификата не выполнена",
	"auto certificate issued":                      "сертификат автоматически выдан",
	"bootstrap admin seed completed":               "стартовый администратор подготовлен",
	"complete enrollment failed":                   "завершение обучения не выполнено",
	"complete enrollment response failed":          "ответ завершения обучения не отправлен",
	"create audit log failed":                      "создание audit log не выполнено",
	"create audit log response failed":             "ответ создания audit log не отправлен",
	"create certificate failed":                    "создание сертификата не выполнено",
	"create certificate response failed":           "ответ создания сертификата не отправлен",
	"create content block failed":                  "создание блока контента не выполнено",
	"create content block response failed":         "ответ создания блока контента не отправлен",
	"create course failed":                         "создание курса не выполнено",
	"create course module failed":                  "создание модуля курса не выполнено",
	"create course module response failed":         "ответ создания модуля курса не отправлен",
	"create course package failed":                 "создание курса с тестом не выполнено",
	"create course package response failed":        "ответ создания курса с тестом не отправлен",
	"create course response failed":                "ответ создания курса не отправлен",
	"create course test failed":                    "привязка теста к курсу не выполнена",
	"create course test response failed":           "ответ привязки теста к курсу не отправлен",
	"create enrollment authorization failed":       "проверка доступа при записи на курс не выполнена",
	"create enrollment failed":                     "запись на курс не выполнена",
	"create enrollment response failed":            "ответ записи на курс не отправлен",
	"create notification failed":                   "создание уведомления не выполнено",
	"create notification response failed":          "ответ создания уведомления не отправлен",
	"create quiz failed":                           "создание теста не выполнено",
	"create quiz response failed":                  "ответ создания теста не отправлен",
	"create review failed":                         "создание отзыва не выполнено",
	"create review response failed":                "ответ создания отзыва не отправлен",
	"create user failed":                           "создание пользователя не выполнено",
	"create user response failed":                  "ответ создания пользователя не отправлен",
	"create webhook failed":                        "создание webhook не выполнено",
	"create webhook response failed":               "ответ создания webhook не отправлен",
	"database migrations applied":                  "миграции базы данных применены",
	"deactivate user failed":                       "отключение пользователя не выполнено",
	"delete content block failed":                  "удаление блока контента не выполнено",
	"delete course module failed":                  "удаление модуля курса не выполнено",
	"delete course test by id failed":              "удаление связи курса и теста по ID не выполнено",
	"delete course test failed":                    "удаление связи курса и теста не выполнено",
	"delete webhook failed":                        "удаление webhook не выполнено",
	"get attempt authorization failed":             "проверка доступа к попытке не выполнена",
	"get attempt failed":                           "получение попытки не выполнено",
	"get attempt response failed":                  "ответ получения попытки не отправлен",
	"get audit log failed":                         "получение audit log не выполнено",
	"get audit log response failed":                "ответ получения audit log не отправлен",
	"get certificate authorization failed":         "проверка доступа к сертификату не выполнена",
	"get certificate failed":                       "получение сертификата не выполнено",
	"get certificate response failed":              "ответ получения сертификата не отправлен",
	"get content block failed":                     "получение блока контента не выполнено",
	"get content block response failed":            "ответ получения блока контента не отправлен",
	"get course failed":                            "получение курса не выполнено",
	"get course module failed":                     "получение модуля курса не выполнено",
	"get course module response failed":            "ответ получения модуля курса не отправлен",
	"get course response failed":                   "ответ получения курса не отправлен",
	"get enrollment authorization failed":          "проверка доступа к записи на курс не выполнена",
	"get enrollment failed":                        "получение записи на курс не выполнено",
	"get enrollment response failed":               "ответ получения записи на курс не отправлен",
	"get notification authorization failed":        "проверка доступа к уведомлению не выполнена",
	"get notification failed":                      "получение уведомления не выполнено",
	"get notification response failed":             "ответ получения уведомления не отправлен",
	"get quiz failed":                              "получение теста не выполнено",
	"get quiz response failed":                     "ответ получения теста не отправлен",
	"get review failed":                            "получение отзыва не выполнено",
	"get review response failed":                   "ответ получения отзыва не отправлен",
	"get user failed":                              "получение пользователя не выполнено",
	"get user response failed":                     "ответ получения пользователя не отправлен",
	"get webhook failed":                           "получение webhook не выполнено",
	"get webhook response failed":                  "ответ получения webhook не отправлен",
	"google config response failed":                "ответ настроек Google не отправлен",
	"google login failed":                          "вход через Google не выполнен",
	"google login response failed":                 "ответ входа через Google не отправлен",
	"health check failed":                          "проверка состояния сервиса не выполнена",
	"http request completed":                       "HTTP запрос обработан",
	"http server shutting down":                    "HTTP сервер останавливается",
	"http server starting":                         "HTTP сервер запускается",
	"http server stopped":                          "HTTP сервер остановлен",
	"list attempts authorization failed":           "проверка доступа к списку попыток не выполнена",
	"list attempts failed":                         "получение списка попыток не выполнено",
	"list attempts response failed":                "ответ списка попыток не отправлен",
	"list audit logs failed":                       "получение списка audit logs не выполнено",
	"list audit logs response failed":              "ответ списка audit logs не отправлен",
	"list certificates authorization failed":       "проверка доступа к списку сертификатов не выполнена",
	"list certificates failed":                     "получение списка сертификатов не выполнено",
	"list certificates response failed":            "ответ списка сертификатов не отправлен",
	"list content blocks failed":                   "получение списка блоков контента не выполнено",
	"list content blocks response failed":          "ответ списка блоков контента не отправлен",
	"list course modules failed":                   "получение списка модулей курса не выполнено",
	"list course modules response failed":          "ответ списка модулей курса не отправлен",
	"list course tests failed":                     "получение связей курса и тестов не выполнено",
	"list course tests response failed":            "ответ связей курса и тестов не отправлен",
	"list courses failed":                          "получение списка курсов не выполнено",
	"list courses response failed":                 "ответ списка курсов не отправлен",
	"list enrollments authorization failed":        "проверка доступа к списку записей на курс не выполнена",
	"list enrollments failed":                      "получение списка записей на курс не выполнено",
	"list enrollments response failed":             "ответ списка записей на курс не отправлен",
	"list notifications authorization failed":      "проверка доступа к списку уведомлений не выполнена",
	"list notifications failed":                    "получение списка уведомлений не выполнено",
	"list notifications response failed":           "ответ списка уведомлений не отправлен",
	"list quizzes failed":                          "получение списка тестов не выполнено",
	"list quizzes response failed":                 "ответ списка тестов не отправлен",
	"list reviews failed":                          "получение списка отзывов не выполнено",
	"list reviews response failed":                 "ответ списка отзывов не отправлен",
	"list users failed":                            "получение списка пользователей не выполнено",
	"list users response failed":                   "ответ списка пользователей не отправлен",
	"list webhooks failed":                         "получение списка webhook не выполнено",
	"list webhooks response failed":                "ответ списка webhook не отправлен",
	"login failed":                                 "вход пользователя не выполнен",
	"login response failed":                        "ответ входа пользователя не отправлен",
	"logout failed":                                "выход пользователя не выполнен",
	"mark notification read authorization failed":  "проверка доступа к отметке уведомления не выполнена",
	"mark notification read failed":                "уведомление не отмечено прочитанным",
	"mark notification read preload failed":        "уведомление не загружено перед отметкой прочтения",
	"mark notification read response failed":       "ответ отметки уведомления не отправлен",
	"me response failed":                           "ответ текущего пользователя не отправлен",
	"moderate review failed":                       "модерация отзыва не выполнена",
	"moderate review response failed":              "ответ модерации отзыва не отправлен",
	"review attempt authorization failed":          "проверка доступа к ревью попытки не выполнена",
	"review attempt failed":                        "ревью попытки не выполнено",
	"review attempt response failed":               "ответ ревью попытки не отправлен",
	"submit attempt authorization failed":          "проверка доступа к отправке попытки не выполнена",
	"submit attempt failed":                        "отправка попытки не выполнена",
	"submit attempt response failed":               "ответ отправки попытки не отправлен",
	"update content block failed":                  "обновление блока контента не выполнено",
	"update content block response failed":         "ответ обновления блока контента не отправлен",
	"update course failed":                         "обновление курса не выполнено",
	"update course module failed":                  "обновление модуля курса не выполнено",
	"update course module response failed":         "ответ обновления модуля курса не отправлен",
	"update course response failed":                "ответ обновления курса не отправлен",
	"update quiz failed":                           "обновление теста не выполнено",
	"update quiz response failed":                  "ответ обновления теста не отправлен",
	"update user failed":                           "обновление пользователя не выполнено",
	"update user response failed":                  "ответ обновления пользователя не отправлен",
	"update webhook failed":                        "обновление webhook не выполнено",
	"update webhook response failed":               "ответ обновления webhook не отправлен",
	"upload failed":                                "загрузка файла не выполнена",
	"upload response failed":                       "ответ загрузки файла не отправлен",
	"verify certificate failed":                    "проверка сертификата не выполнена",
	"verify certificate response failed":           "ответ проверки сертификата не отправлен",
	"webhook delivery failed":                      "доставка webhook не выполнена",
	"write health response failed":                 "ответ health check не отправлен",
}
